### ISSUE TITLE
FEELnc pipeline can use of without a reference genome？

### ISSUE THREAD

**Issue by tiramisutes** [tderrien/FEELnc#14]
Hello,
In the [README.md](https://github.com/tderrien/FEELnc/blob/master/README.md) file you mean this pipeline can use of without a reference genome. But I read all the file and find it need ``ref_annotation.GTF`` and ``ref_genome.FASTA`` as mandatory arguments.

**Comment by vwucher** [comment]
Hello,

The FEELnc_codpot.pl (coding potential) can be used without a GTF file. The GTF is only mandatory for FEELnc_filter.pl and FEELnc_classifier.pl, because the purpose of the two modules is to check the intersection/relation of the "new" annotation and the reference annotation.

Regarding FEELnc_codpot.pl, it can be used with only a FASTA file of the mRNA sequences. The annotation in GTF is only mandatory if you want that FEELnc extract the mRNA sequences for you.
Below are some examples:

With only FASTA file of mRNA and lncRNA sequences:
FEELnc_codpot.pl -i candidate_new_transcripts.fa -a -l known_mRNA.fa -l known_lncRNA.fa

With the annotation of mRNA and lncRNA and the genome sequence:
FEELnc_codpot.pl -i candidate_new_transcripts.fa -a known_mRNA.gtf -l known_lncRNA.gtf -g ref_genome.fa

If you don't have a set of lncRNAs, you can use the shuffling option instead of the lncRNA sequences/reference file:
--mode=shuffle
instead of
-l known_lncRNA.fa or -l known_lncRNA.gtf

Regards,
Valentin Wucher

**Comment by tiramisutes** [comment]
Thanks for your explanation.
