### ISSUE TITLE
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :"unable to start device PNG. 

### ISSUE THREAD

**Issue by dengpingchuan** [tderrien/FEELnc#21]
Hi Tderrien,
There was one problem when running the  ‘**Coding_Potential**‘ module, as follows: **"Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :"unable to start device PNG.** I have tried to generate png() but failed. Is there any solution to sovle this problem? such as skipping build png or replace png by pdf?  Could you give any suggestion. 
Your reply will be appreciated!

**Comment by tderrien** [comment]
Dear Deng Pingchuan,

First of all, thank you for using our tool FEELnc.
Regarding the issue you mentioned, it is more related to your X11 device rather than FEELnc (i.e if you manage to build whatever .png image using your R version, FEELnc will be running correctly).
However, if you really need to build .pdf, you can directly replace _png_ by _pdf_ in the 2 R scripts from your FEELnc/utils directory:
* R script = **codpot_randomforest_2thres.r** : 
Here are the line number (first column) and the modification in bold:

```
30 outVar           <- paste(file_path_sans_ext(outFile), "_varImpPlot.**pdf**", sep="")
31 outROC           <- paste(file_path_sans_ext(outFile), "_TGROC.**pdf**", sep="")
214 **pdf**(outROC, h=800, w=800)
280 **pdf**(outVar, h=800, w=800)
```

* R script = **codpot_randomforest.r** : 
```
24 outVar           <- paste(file_path_sans_ext(outFile), "_varImpPlot.**pdf**", sep="")
25 outROC           <- paste(file_path_sans_ext(outFile), "_TGROC.**pdf**", sep="")
194 **pdf**(outROC, h=800, w=800)
246 **pdf**(outVar, h=800, w=800)
```

**Comment by dengpingchuan** [comment]
Dear Tderrien,
I am appreciated for your kindly help. Now, the problem has been sovled following your suggestions.

Best,
Pingchuan
