### ISSUE TITLE
Cannot run FEELnc_codpot.pl

### ISSUE THREAD

**Issue by bodhi84** [tderrien/FEELnc#27]
Hi
I am working on the Zebrafish lncRNA and have recently installed your software. The first step of the pipeline is running smoothly and producing the desired output. But, whenever I am trying to run the next step i.e. FEELnc_codpot.pl I am getting the following error:

**Undefined subroutine &Bio::DB::IndexedBase::_strip_crnl called at /usr/local/share/perl/5.26.1/Bio/DB/Fasta.pm line 295.**

I have tried running the test with toy samples and there also I am getting the same error. 

I would appreciate your help very much.

**Comment by vwucher** [comment]
Hi,

Thanks for using FEELnc.
Concerning your error, it seems to me that it is maybe related to a previous error.
Now, in order to avoid this error, the affectation of the `PERL5LIB` variable should be done in the following order (taking from the FEELnc GitHub main page):
`export PERL5LIB=$PERL5LIB:${FEELNCPATH}/lib/ #order is important to avoid &Bio::DB::IndexedBase::_strip_crnl error with bioperl >=v1.7`

Do you export your variable in this order? If not, can you try and tell us if it is working correctly?

Thanks! Have a good day,
Valentin

**Comment by bodhi84** [comment]
Hello,
Thank you for your prompt reply. As per your suggestion, I have again exported the variables in the same order as mentioned in the FEELnc GitHub main page. But, it is again giving the same error.

Regards,
Bodhisattwa

**Comment by vwucher** [comment]
Hi,

What is your version of BioPerl? Is it at least `BioPerl-1.6.924`? Sorry for those questions but it is to check 'usual' mistakes.

Thanks,
Valentin

**Comment by bodhi84** [comment]
Hi Valentin,
I have checked the BioPerl version and it is the recent version i.e. 1.007002. 
Thanks and Regards,
Bodhisattwa

**Comment by tderrien** [comment]
Hi @bodhi84,
Coul you paste the output of this command line:
`echo $PERL5LIB`

Thanks

**Comment by tderrien** [comment]
Ok, then to be sure both FEELnc lib and bioperl lib are exported correctly, you could try :

`
export PERL5LIB=/usr/local/share/perl/5.26.1:/home/zoology/Documents/FEELnc/lib/
`

Let us know if this helped.

Best

**Comment by bodhi84** [comment]
Hi tderrien,

Thank you very much for the solution. After exporting, it is working like a charm. It is indeed a great software and I am looking forward to get wonderful results using it.

Thanks again.
Bodhisattwa

**Comment by tderrien** [comment]
Great, happy it helped
