### ISSUE TITLE
exonic_lncRNAs

### ISSUE THREAD

**Issue by Simon602** [tderrien/FEELnc#36]
Dear All

I got a list of candidate lncRNAs from FEELnc, but I have some lncRNA which they are matched with exons but plus/minus (according to the blast results) , how I can be determined these are antisense exonic lncRNA and NOT a cleaved or degraded mRNA?

according to the GTF file of candidate lncRNAs, I have more than one transcript for some lncRNA genes but with few bp different in length. for examples: A.1 , A.2 , A.3 for lncRNA A gene. should I consider them as 3 lncRNAs or just take the longest one?

Thanks

**Comment by tderrien** [comment]
Hello Simon,

> I got a list of candidate lncRNAs from FEELnc, but I have some lncRNA which they are matched with exons but plus/minus (according to the blast results) , how I can be determined these are antisense exonic lncRNA and NOT a cleaved or degraded mRNA?

Depending on you analysis, you might have lncRNAs overlapping mRNAs (protein-coding) in antisense or in sense (intronic). They shouldn't match mRNA exons because the 1st step of the pipeline (FEElnc_filter.pl) would normally remove them.

> according to the GTF file of candidate lncRNAs, I have more than one transcript for some lncRNA genes but with few bp different in length. for examples: A.1 , A.2 , A.3 for lncRNA A gene. should I consider them as 3 lncRNAs or just take the longest one?

Indeed, transcriptome reconstruction tools (_e.g._ cufflinks, stringtie...) sometimes produce almost similar alternative isoforms. The fate of these depends on the downstream analysis.

Best,

Thomas
