### ISSUE TITLE
Issue with FEELnc_codpot spethres option.

### ISSUE THREAD

**Issue by ttttuck** [tderrien/FEELnc#57]
Hello,

How are you?

I'm facing an issue when running the FEELnc_codpot module to find new human noncoding transcripts. I'm running the following code:

`FEELnc_codpot.pl -i humanPutativeLncRNAs.gtf -a gencode.v41.pc_transcripts.fa -g GRCh38.primary_assembly.genome.fa -l gencode.v41.lncRNA_transcripts.fa -n 5000,5000 --spethres=0.85,0.85`

And I'm not getting the 85% Se/Sp TG-ROC and two cutoffs. The program is providing only the 95% Se/Sp and one cutoff stating that this is the best value. I know it is but I want to see how it goes when I set the Se/Sp to 85%.

> WARNING: the value where sensitivity equal specicifity: '0.9499412' is greater than the specificity threshold: mRNA: '0.85'; lncRNA: '0.85'. Use the best value.

> WARNING: the threshold obtain for mRNA '0.389' is lesser than the the one for lncRNA '0.389'. Use the threshold '0.389' where sensitivity equal to specicifity for mRNA: '0.9499412'.

How can I "force" the code to provide me a 85% Se/Sp TG-ROC curve and two cutoffs?

Thanks in advance

Tlucky

**Comment by vwucher** [comment]
Hi @TluckDucky,

Apparently it seems that the issue here is that, since the two values you provided (0.85) are lower than the value obtain with the best threshold (0.95), i.e. when Se==Sp, then we force it to have only one threshold. Because here, if FEELnc used the thresholds obtained for 0.85 Se/Sp, then you will have some transcripts that will be both mRNA and lncRNA. That's why we decided to enforce this.
If you want to get them anyway, you can modify [codpot_randomforest_2thres.r](https://github.com/tderrien/FEELnc/tree/master/utils/codpot_randomforest_2thres.r) and write the `S` and `P` R objects, they should contain the sensitivity and specificity of the transcripts as well as their names/ids (or others but normally it should be them). Then you can put manually the thresholds you want.

Hope this help!
Bye,
Valentin
