### ISSUE TITLE
error msg (in cleanup)

### ISSUE THREAD

**Issue by ls233** [tderrien/FEELnc#7]
(in cleanup) Can't call method "close" on an undefined value at /path/to/CPAN/5.10.1/lib/perl5/Bio/DB/SeqFeature/Store/berkeleydb.pm line 1455.

I'd be happy to provide some run info, if needed.

**Comment by tderrien** [comment]
Hello,
Thank you for reporting this warning which was also reported in README.md (end of FEELNc_classifier module)
Actually, it seems related to the bioperl version used to run the classifier. But it does not impact the results since lncRNAs:mRNAs interactions should be written in the output file.
HTH
